### ISSUE TITLE
getting malloc.c error after compiling on aarch64

### ISSUE THREAD

**Issue by ntzb** [mwh/retail#4]
Hi, I am trying to make retail work on my aarch64 machine.
I followed the build instructions, but since "cc" is not defined, I changed it to "gcc".
after compiling and trying to use the "-f" option, I get:
retail: malloc.c:2868: mremap_chunk: Assertion `((size + offset) & (GLRO (dl_pagesize) - 1)) == 0' failed.

what is going on?

**Comment by mwh** [comment]
I don’t get that error with either `retail -f file` or `nl file | retail -f` on ARM, but I really would not be surprised if there’s a malloc bug that just doesn’t show up usually.

If you could provide a specific failing command that might help to track it down if there’s some complex interaction. Even better, if you could run the command under valgrind it ought to point you at something that’s wrong.

**Comment by ntzb** [comment]
my command is:
`retail -f /storage/process.log`
I am working on a limited system, which does not have every package available for install.
valgrind exists, but trying to use it on retail gives an error on missing libc-debug, because strlen is missing from my ld-linux-aarch64.so.1.
it suggests I install glibc-debuginfo or libc6-dbg, but neither (or similar) is available in my environment.

`valgrind:  A must-be-redirected function
valgrind:  whose name matches the pattern:      strlen
valgrind:  in an object with soname matching:   ld-linux-aarch64.so.1
valgrind:  was not found whilst processing
valgrind:  symbols from the object with soname: ld-linux-aarch64.so.1`

**Comment by ntzb** [comment]
I tried to get some more hints of why it does not work.
I set up a different aarch64 test env, and tried compiling it there.
it works there, and runs as it should.
trying to copy the compiled file (with `make SHARED=0 CC='gcc -static'`) to the real env results in the same malloc error.
so it's something about the real (yet limited) env. 

does this help?

**Comment by mwh** [comment]
I ran valgrind elsewhere and fixed a memory error - it might be the one you're seeing, or it might not. Can you try again with the latest head? With any luck that has resolved the issue.

**Comment by ntzb** [comment]
this fixed it.
thanks!
